openapi: 3.0.1
info:
  title: Ping API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /{ping}:
    get:
      description: Retourne une chaine de caractère
      responses:
        '200':
          description: Reponse retournée
          content:
            text/plain:
              schema:
                type: string
                example: pong

